services:
  grafana:
    image: grafana/grafana:latest
    container_name: ssv-grafana
    restsart: unless-stopped
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - ${GRAFANA_SERVER_PORT:-3000}:3000
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: ssv-prometheus
    restart: unless-stopped
    ports:
      - ${PROM_SERVER_PORT:-9090}:9090
    volumes:
      - prometheus-volume:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus/rules:/etc/prometheus/rules
    command:
      - --web.enable-lifecycle
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=${PROM_RETENTION_TIME:-1w}
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ssv-alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager-volume:/alertmanager
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yaml
    networks:
      - monitor-net
    depends_on:
      - prometheus
    ports:
      - ${ALERTMANAGER_SERVER_PORT:-9093}:9093

volumes:
  grafana-volume:
    name: grafana-volume
  prometheus-volume:
    name: prometheus-volume
  alertmanager-volume:
    name: alertmanager-volume

networks:
  monitor-net:
    name: monitor-net
    driver: bridge
